version: 1
runtime: python27
api_version: 1
threadsafe: false
# [START handlers]
handlers:
- url: /.*
  script: /wsgi/application.py
# [END handlers]

# [START libraries]
libraries:
- name: jinja2
  version: 2.7.3
- name: numpy
  version: 1.9.1
- name: cherrypy
  version: 3.6.0
# [END libraries]
