version: 1
runtime: python27
api_version: 1
threadsafe: false
# [START handlers]
handlers:
- url: /.*
  script: /wsgi/application.py
# [END handlers]

# [START libraries]
#libraries:
# [END libraries]
