version: 1
runtime: python27
api_version: 1
# [START handlers]
handlers:
- url: /.*
  script: application.py
# [END handlers]

# [START libraries]
libraries:
- name: jinja2
  version: latest
# [END libraries]
